### ISSUE TITLE
[Epic] Move KMC out of control-plane

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma-metrics-collector#17]
- [x] https://github.com/kyma-project/control-plane/issues/3327
- [x] https://github.com/kyma-project/control-plane/issues/3330
- [x] https://github.com/kyma-project/control-plane/issues/3400
- [x] https://github.com/kyma-project/kyma-metrics-collector/issues/13
